language: generic
dist: trusty
env:
  - EMACS=emacs
  - EMACS=emacs-snapshot
matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot
before_install:
  # Nightly Emacs snapshot builds
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}
  # Install and bootstrap cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask install
script:
  - cask exec ert-runner
